# Generated by Django 3.2.8 on 2021-10-24 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='place',
            name='dpto',
        ),
        migrations.AddField(
            model_name='place',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
