# Generated by Django 3.2.8 on 2021-11-03 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='calificacion',
            new_name='calification',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='muni',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='lugar',
            new_name='place_name',
        ),
    ]
