# Generated by Django 3.2.8 on 2021-10-13 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['create_time']},
        ),
    ]
