# Generated by Django 3.2.8 on 2021-10-14 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='highlighted',
        ),
        migrations.RemoveField(
            model_name='user',
            name='owner',
        ),
    ]
