# Generated by Django 3.2.8 on 2021-10-13 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['create']},
        ),
        migrations.RenameField(
            model_name='user',
            old_name='create_time',
            new_name='create',
        ),
    ]
