# Generated by Django 3.2.8 on 2021-10-24 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211024_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='img',
        ),
        migrations.RemoveField(
            model_name='place',
            name='img2',
        ),
        migrations.AddField(
            model_name='place_activity',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='place_activity',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
