# Generated by Django 3.2.8 on 2021-10-22 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211021_0035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='tyactivity',
        ),
        migrations.AddField(
            model_name='activity',
            name='name',
            field=models.TextField(default='ecoturism', max_length=200),
        ),
    ]
