# Generated by Django 3.2.8 on 2021-10-26 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211026_1742'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hostels',
            new_name='Hostel',
        ),
    ]
