# Generated by Django 3.2.8 on 2021-10-25 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211024_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='create',
        ),
    ]
