# Generated by Django 3.2.8 on 2021-10-26 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_hostels_hostel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel',
            name='idcity',
        ),
    ]
